project_name: Black Mailbox
email: kr3ssh@gmail.com
gpg_key: |
  -----BEGIN PGP PUBLIC KEY BLOCK-----
  Version: GnuPG v2

  mQINBFa3hSIBEADuu2kQCPYxfLbSYTSl1aZoqV5qbu83V3iGRkO6S3rup/anGtJB
  DwF3tJcl17duYr2/w1cA5zAjxOyxA1qP3rs9vSxnqau8/5oPH186zIZfeEt5oHQ6
  yZ4MeCpgyxBYucgu5sEps/nuzz+xJ4UHbAo23SPi2Onj1cp2JLlV5y2U0s/rNMpR
  Ar/Yan73v+LS78meNuIct9Vv+K60Fi7KXiSb6nK0uS7LAIR4ZBsDFDie/kcW8LZv
  pma59e8i2KSXz4gN8obH6FfQ31kko+DM9TCp5nrY3rCUAXmN48ox1EDyrTEYWRv8
  KylcpTCCAKfHw5ln/eoYyqISrPmwAPUS4VLwXGO9e1Q1+o4WjTz5FNRk7TqGveWb
  FYGumVr2sfSlUjbdZ/hlN32fydA9kiQIHf42Za5iN2Nta77IcXV+oSlsHLNjW0ly
  KaWRTQRgBha+FuAUnD2QNTwv9XC4DshqGwrBXNrSGrNyXsSBmZM6WD9gis0Dyi/S
  0D3J7QfvNPnjhWE0Ru/4RkYkswW/7xRNmL3PvU5bH3d8p5O+S0hkzrwJRPQrYWK0
  Ay4j7ltd451OZOYeROPSb8gg7rY+HDr4qoyYUPGao9dDHojlxGvuKj9I3oF7sHQN
  j9blOZLaHbamH49ip53tPXXM6qwDrd4we5ezLUT5hF6jUnksiMghnOsbNwARAQAB
  tDVTZXJnZXkgQmVzZWRpbiAoQmxhY2sgTWFpbGJveCBrZXkpIDxrcjNzc2hAZ21h
  aWwuY29tPokCNwQTAQoAIQUCVreFIgIbAwULCQgHAwUVCgkICwUWAgMBAAIeAQIX
  gAAKCRAouIj7MqFZwbdSD/9n2sHReyw6CA0AMBncxgwYAr5i2QyI1vD4Db1yA8xF
  f0neevQ1MLkZESMKqtUvSMrh7aa2FERnCSZPhqP71xpFtP7G/2dXSrQxfqihPNtq
  6LcXrXLIZoO4xrIwxkIRn3R6aDUgixPrl1flOMhe/gDvnyfh6XwEjTvhVU7mBZO/
  mz/2dEdiWlYZkuRsgjfu/DWzlyjx3jGTzuqNgCPjiz97BguzIuAIpeOu0jemEwvC
  +rN+JEfbywYHA7h0uLRyAUl4/s0wOz2tkYqythlwzdKDHYf2X3NFKsnpasNcJhhg
  6eK/QwsN9w2L5RVgf2pnUi4n1PkQpaMzg+v64/gZf668iZro+Ri+Uhe+V9vPhExc
  4wa/MmrZoqYKOCsIW7FCUGeNFHlCaWInee5oskuHkXY+ok7IFpjkkZoKTP23zO3b
  oShAbRvJ5aEGe+cd80vkSfOy7UCv0md7dii4LJMhVfuXhngQ17rsmGe0ZhEipv4H
  UbnyxSRi09SRwMa/Y9UekcVgnGz0mEP0Lb+lOaC9ppM/wQrt9sIoQ0LWMpbMIk7S
  /6MfNd7La8O/1hFvXg1c9j9yvb2VI75CcSYsnUjCCKV3aRZ8ZRiaFO6KdrhCiMsm
  CpOVXzO+pn6JjZKrsWHq8HJ5ENIrFaV3Of61np5odUG20tVOuXD2b3uvKXAxQbvy
  NLkCDQRWt4UiARAAoOI3BLrw5bDw/cie83xYwbaaJuj2Y8dodeEw/mTeQE4sSvSw
  6jHxga5lOEm57qteOPRFVmqZNDdZr8otC9im2wmhYGZXuF+dposw6dh+oRu8Hvs0
  MCML2ZUQ6XqvfK2W9kPvvYeicCSd+UvymIoWYwPqO5ropXtaP4TTLLcn/nLji3Zo
  P7Fkf8zuR5U5G4yZhHx7Ih57T4woUdDnUOpiCfJxcdtHvJqtVl/ubOS7N3nf5EBG
  xsrl7Eu8q8+O2eleVkxyzu9+3n6YAZKKmJmdMa7lTpT5uuVUk6N13Lk4kPrKTBEV
  wPD4BLx1utcPZMEEdUaaFoylIYiZO9a77Gc0aK/T0ZnUPMO8vQfgT6t9C4EM+mpx
  zcM//CdX2MaksBV6Dq42lkwkEopkdXZVmjDY4BWYvGjVYwU2V2SDt6a8RqGqtvHG
  VPBYNru0CI5Vd398oyQdq1/G+Ycs0YMyBHDqfBXTKJacK52lpnPPYmH/FN3W91TL
  eoB1PuJNRdBC1e39YFdbijcz36helXy4YysJ+/gn6czB2HzVMwyc3gRqx9K/MG+e
  +BRql6u/t0IgMfCKYoJ4d7F2Jkftc+JmCIpBPOnWk5MSA83Qbt/pmZgfxhufv/2s
  gi/P0t6Kk31ZSJQQYFD3t4QOelcO8Xxcyf3z++Co2cSDOALdKWQOZ03ZA+UAEQEA
  AYkCHwQYAQoACQUCVreFIgIbDAAKCRAouIj7MqFZwYHgEAC3j7m1+JOmpAHlr7T9
  o2P9ihrqJaAOGZZx1lysaklMtBPK4DhmEs9iUEEZWlFe3Q0vfY7wlF2piXwAoo4k
  Rdw0r7B2ZLwWqqUc48FNEoU8U7wklapaQKCLTNOIPcuDht5A/Vuk8zmlOoDNhgg4
  oHkqaobPykk1Pgvj9Tlik976UN+icir2AHd1xB0+yk1xAnsB9YeQW4aQ/3TI63FZ
  bvr9L2MXjv3kQXxxAcJmVpuniCFLSech1nUytsYqAQMzDUoUZFLAIZ4IIR6OHfJ2
  CFSKRNgQE7TXJ0n+qnBRM4IZY93eEkFmJLZhCDA9Mhjqhnsns8ZvgNhPzXHUappA
  peRHBWsDH4J65whRtmsNh0rFomS6RGW6TsbqEYh26DU42s/8BsUeSAkGCEv5Hx5L
  b7Bi9OA+R1ugUVc7IqnpdYkH1hCQTsJporXgEvyxz4TzpAJHh1quhAcQO1/lMcm0
  VoQZPEa7Z+n2D4So8SPvYzxXm5mc1GQH/8MK0jWkLU7MfD4HGDpe6wrnj7j0GL/W
  3AU8C1aUEkFaXkZ4/p7soSkidLU9825KnDvTBu1ggViNy3o/YiSsqUywzroNqav6
  TcYucglovlHaJHSF04MxvsPttQImN294JIF7x337MtrLXs8R/kReuF7ORrKWFMhQ
  BnDDI5WVr4V5dhGriu2ikzsWxQ==
  =DtMN
  -----END PGP PUBLIC KEY BLOCK-----
